// ignore_for_file: constant_identifier_names, non_constant_identifier_names
enum Countries {
  Aruba("AW", "ABW", "Aruba"),
  Afghanistan("AF", "AFG", "Afghanistan"),
  Angola("AO", "AGO", "Angola"),
  Anguilla("AI", "AIA", "Anguilla"),
  Aland_Islands("AX", "ALA", "Aland Islands"),
  Albania("AL", "ALB", "Albania"),
  Andorra("AD", "AND", "Andorra"),
  United_Arab_Emirates("AE", "ARE", "United Arab Emirates"),
  Argentina("AR", "ARG", "Argentina"),
  Armenia("AM", "ARM", "Armenia"),
  American_Samoa("AS", "ASM", "American Samoa"),
  Antarctica("AQ", "ATA", "Antarctica"),
  French_Southern_and_Antarctic_Lands(
      "TF", "ATF", "French Southern and Antarctic Lands"),
  Antigua_and_Barbuda("AG", "ATG", "Antigua and Barbuda"),
  Australia("AU", "AUS", "Australia"),
  Austria("AT", "AUT", "Austria"),
  Azerbaijan("AZ", "AZE", "Azerbaijan"),
  Burundi("BI", "BDI", "Burundi"),
  Belgium("BE", "BEL", "Belgium"),
  Benin("BJ", "BEN", "Benin"),
  Burkina_Faso("BF", "BFA", "Burkina Faso"),
  Bangladesh("BD", "BGD", "Bangladesh"),
  Bulgaria("BG", "BGR", "Bulgaria"),
  Bahrain("BH", "BHR", "Bahrain"),
  Bahamas("BS", "BHS", "Bahamas"),
  Bosnia_and_Herzegovina("BA", "BIH", "Bosnia and Herzegovina"),
  Saint_Barthelemy("BL", "BLM", "Saint Barthelemy"),
  Saint_Helena("SH", "SHN", "Saint Helena, Ascension and Tristan da Cunha"),
  Belarus("BY", "BLR", "Belarus"),
  Belize("BZ", "BLZ", "Belize"),
  Bermuda("BM", "BMU", "Bermuda"),
  Bolivia("BO", "BOL", "Bolivia"),
  Caribbean_Netherlands("BQ", "BES", "Caribbean Netherlands"),
  Brazil("BR", "BRA", "Brazil"),
  Barbados("BB", "BRB", "Barbados"),
  Brunei("BN", "BRN", "Brunei"),
  Bhutan("BT", "BTN", "Bhutan"),
  Bouvet_Island("BV", "BVT", "Bouvet Island"),
  Botswana("BW", "BWA", "Botswana"),
  Central_African_Republic("CF", "CAF", "Central African Republic"),
  Canada("CA", "CAN", "Canada"),
  Cocos_Islands("CC", "CCK", "Cocos (Keeling) Islands"),
  Switzerland("CH", "CHE", "Switzerland"),
  Chile("CL", "CHL", "Chile"),
  China("CN", "CHN", "China"),
  Ivory_Coast("CI", "CIV", "Ivory Coast"),
  Cameroon("CM", "CMR", "Cameroon"),
  Congo_Kinshasa("CD", "COD", "Congo-Kinshasa"),
  Congo_Brazzaville("CG", "COG", "Congo-Brazzaville"),
  Cook_Islands("CK", "COK", "Cook Islands"),
  Colombia("CO", "COL", "Colombia"),
  Comoros("KM", "COM", "Comoros"),
  Cape_Verde("CV", "CPV", "Cape Verde"),
  Costa_Rica("CR", "CRI", "Costa Rica"),
  Cuba("CU", "CUB", "Cuba"),
  Curacao("CW", "CUW", "Curacao"),
  Christmas_Island("CX", "CXR", "Christmas Island"),
  Cayman_Islands("KY", "CYM", "Cayman Islands"),
  Cyprus("CY", "CYP", "Cyprus"),
  Czechia("CZ", "CZE", "Czechia"),
  Germany("DE", "DEU", "Germany"),
  Djibouti("DJ", "DJI", "Djibouti"),
  Dominica("DM", "DMA", "Dominica"),
  Denmark("DK", "DNK", "Denmark"),
  Dominican_Republic("DO", "DOM", "Dominican Republic"),
  Algeria("DZ", "DZA", "Algeria"),
  Ecuador("EC", "ECU", "Ecuador"),
  Egypt("EG", "EGY", "Egypt"),
  Eritrea("ER", "ERI", "Eritrea"),
  Western_Sahara("EH", "ESH", "Western Sahara"),
  Spain("ES", "ESP", "Spain"),
  Estonia("EE", "EST", "Estonia"),
  Ethiopia("ET", "ETH", "Ethiopia"),
  Finland("FI", "FIN", "Finland"),
  Fiji("FJ", "FJI", "Fiji"),
  Falkland_Islands("FK", "FLK", "Falkland Islands"),
  France("FR", "FRA", "France"),
  Faroe_Islands("FO", "FRO", "Faroe Islands"),
  Micronesia("FM", "FSM", "Micronesia"),
  Gabon("GA", "GAB", "Gabon"),
  United_Kingdom("GB", "GBR", "United Kingdom"),
  Georgia("GE", "GEO", "Georgia"),
  Guernsey("GG", "GGY", "Guernsey"),
  Ghana("GH", "GHA", "Ghana"),
  Gibraltar("GI", "GIB", "Gibraltar"),
  Guinea("GN", "GIN", "Guinea"),
  Guadeloupe("GP", "GLP", "Guadeloupe"),
  Gambia("GM", "GMB", "Gambia"),
  Guinea_Bissau("GW", "GNB", "Guinea-Bissau"),
  Equatorial_Guinea("GQ", "GNQ", "Equatorial Guinea"),
  Greece("GR", "GRC", "Greece"),
  Grenada("GD", "GRD", "Grenada"),
  Greenland("GL", "GRL", "Greenland"),
  Guatemala("GT", "GTM", "Guatemala"),
  French_Guiana("GF", "GUF", "French Guiana"),
  Guam("GU", "GUM", "Guam"),
  Guyana("GY", "GUY", "Guyana"),
  Hong_Kong("HK", "HKG", "Hong Kong"),
  Heard_Island_and_McDonald_Islands(
      "HM", "HMD", "Heard Island and McDonald Islands"),
  Honduras("HN", "HND", "Honduras"),
  Croatia("HR", "HRV", "Croatia"),
  Haiti("HT", "HTI", "Haiti"),
  Hungary("HU", "HUN", "Hungary"),
  Indonesia("ID", "IDN", "Indonesia"),
  Isle_of_Man("IM", "IMN", "Isle of Man"),
  India("IN", "IND", "India"),
  British_Indian_Ocean_Territory("IO", "IOT", "British Indian Ocean Territory"),
  Ireland("IE", "IRL", "Ireland"),
  Iran("IR", "IRN", "Iran"),
  Iraq("IQ", "IRQ", "Iraq"),
  Iceland("IS", "ISL", "Iceland"),
  Israel("IL", "ISR", "Israel"),
  Italy("IT", "ITA", "Italy"),
  Jamaica("JM", "JAM", "Jamaica"),
  Jersey("JE", "JEY", "Jersey"),
  Jordan("JO", "JOR", "Jordan"),
  Japan("JP", "JPN", "Japan"),
  Kazakhstan("KZ", "KAZ", "Kazakhstan"),
  Kenya("KE", "KEN", "Kenya"),
  Kyrgyzstan("KG", "KGZ", "Kyrgyzstan"),
  Cambodia("KH", "KHM", "Cambodia"),
  Kiribati("KI", "KIR", "Kiribati"),
  Saint_Kitts_and_Nevis("KN", "KNA", "Saint Kitts and Nevis"),
  South_Korea("KR", "KOR", "South Korea"),
  Kosovo("XK", "UNK", "Kosovo"),
  Kuwait("KW", "KWT", "Kuwait"),
  Laos("LA", "LAO", "Laos"),
  Lebanon("LB", "LBN", "Lebanon"),
  Liberia("LR", "LBR", "Liberia"),
  Libya("LY", "LBY", "Libya"),
  Saint_Lucia("LC", "LCA", "Saint Lucia"),
  Liechtenstein("LI", "LIE", "Liechtenstein"),
  Sri_Lanka("LK", "LKA", "Sri Lanka"),
  Lesotho("LS", "LSO", "Lesotho"),
  Lithuania("LT", "LTU", "Lithuania"),
  Luxembourg("LU", "LUX", "Luxembourg"),
  Latvia("LV", "LVA", "Latvia"),
  Macau("MO", "MAC", "Macau"),
  Saint_Martin("MF", "MAF", "Saint Martin"),
  Morocco("MA", "MAR", "Morocco"),
  Monaco("MC", "MCO", "Monaco"),
  Moldova("MD", "MDA", "Moldova"),
  Madagascar("MG", "MDG", "Madagascar"),
  Maldives("MV", "MDV", "Maldives"),
  Mexico("MX", "MEX", "Mexico"),
  Marshall_Islands("MH", "MHL", "Marshall Islands"),
  North_Macedonia("MK", "MKD", "North Macedonia"),
  Mali("ML", "MLI", "Mali"),
  Malta("MT", "MLT", "Malta"),
  Myanmar("MM", "MMR", "Myanmar"),
  Montenegro("ME", "MNE", "Montenegro"),
  Mongolia("MN", "MNG", "Mongolia"),
  Northern_Mariana_Islands("MP", "MNP", "Northern Mariana Islands"),
  Mozambique("MZ", "MOZ", "Mozambique"),
  Mauritania("MR", "MRT", "Mauritania"),
  Montserrat("MS", "MSR", "Montserrat"),
  Martinique("MQ", "MTQ", "Martinique"),
  Mauritius("MU", "MUS", "Mauritius"),
  Malawi("MW", "MWI", "Malawi"),
  Malaysia("MY", "MYS", "Malaysia"),
  Mayotte("YT", "MYT", "Mayotte"),
  Namibia("NA", "NAM", "Namibia"),
  New_Caledonia("NC", "NCL", "New Caledonia"),
  Niger("NE", "NER", "Niger"),
  Norfolk_Island("NF", "NFK", "Norfolk Island"),
  Nigeria("NG", "NGA", "Nigeria"),
  Nicaragua("NI", "NIC", "Nicaragua"),
  Niue("NU", "NIU", "Niue"),
  Netherlands("NL", "NLD", "Netherlands"),
  Norway("NO", "NOR", "Norway"),
  Nepal("NP", "NPL", "Nepal"),
  Nauru("NR", "NRU", "Nauru"),
  New_Zealand("NZ", "NZL", "New Zealand"),
  Oman("OM", "OMN", "Oman"),
  Pakistan("PK", "PAK", "Pakistan"),
  Panama("PA", "PAN", "Panama"),
  Pitcairn_Islands("PN", "PCN", "Pitcairn Islands"),
  Peru("PE", "PER", "Peru"),
  Philippines("PH", "PHL", "Philippines"),
  Palau("PW", "PLW", "Palau"),
  Papua_New_Guinea("PG", "PNG", "Papua New Guinea"),
  Poland("PL", "POL", "Poland"),
  Puerto_Rico("PR", "PRI", "Puerto Rico"),
  North_Korea("KP", "PRK", "North Korea"),
  Portugal("PT", "PRT", "Portugal"),
  Paraguay("PY", "PRY", "Paraguay"),
  Palestine("PS", "PSE", "Palestine"),
  French_Polynesia("PF", "PYF", "French Polynesia"),
  Qatar("QA", "QAT", "Qatar"),
  Reunion("RE", "REU", "Reunion"),
  Romania("RO", "ROU", "Romania"),
  Russia("RU", "RUS", "Russia"),
  Rwanda("RW", "RWA", "Rwanda"),
  Saudi_Arabia("SA", "SAU", "Saudi Arabia"),
  Sudan("SD", "SDN", "Sudan"),
  Senegal("SN", "SEN", "Senegal"),
  Singapore("SG", "SGP", "Singapore"),
  South_Georgia("GS", "SGS", "South Georgia"),
  Svalbard_and_Jan_Mayen("SJ", "SJM", "Svalbard and Jan Mayen"),
  Solomon_Islands("SB", "SLB", "Solomon Islands"),
  Sierra_Leone("SL", "SLE", "Sierra Leone"),
  El_Salvador("SV", "SLV", "El Salvador"),
  San_Marino("SM", "SMR", "San Marino"),
  Somalia("SO", "SOM", "Somalia"),
  Saint_Pierre_and_Miquelon("PM", "SPM", "Saint Pierre and Miquelon"),
  Serbia("RS", "SRB", "Serbia"),
  South_Sudan("SS", "SSD", "South Sudan"),
  Sao_Tome_and_Principe("ST", "STP", "Sao Tome and Principe"),
  Suriname("SR", "SUR", "Suriname"),
  Slovakia("SK", "SVK", "Slovakia"),
  Slovenia("SI", "SVN", "Slovenia"),
  Sweden("SE", "SWE", "Sweden"),
  Eswatini("SZ", "SWZ", "Eswatini"),
  Sint_Maarten("SX", "SXM", "Sint Maarten"),
  Seychelles("SC", "SYC", "Seychelles"),
  Syria("SY", "SYR", "Syria"),
  Turks_and_Caicos_Islands("TC", "TCA", "Turks and Caicos Islands"),
  Chad("TD", "TCD", "Chad"),
  Togo("TG", "TGO", "Togo"),
  Thailand("TH", "THA", "Thailand"),
  Tajikistan("TJ", "TJK", "Tajikistan"),
  Tokelau("TK", "TKL", "Tokelau"),
  Turkmenistan("TM", "TKM", "Turkmenistan"),
  Timor_Leste("TL", "TLS", "Timor-Leste"),
  Tonga("TO", "TON", "Tonga"),
  Trinidad_and_Tobago("TT", "TTO", "Trinidad and Tobago"),
  Tunisia("TN", "TUN", "Tunisia"),
  Turkey("TR", "TUR", "Turkey"),
  Tuvalu("TV", "TUV", "Tuvalu"),
  Taiwan("TW", "TWN", "Taiwan"),
  Tanzania("TZ", "TZA", "Tanzania"),
  Uganda("UG", "UGA", "Uganda"),
  Ukraine("UA", "UKR", "Ukraine"),
  United_States_Minor_Outlying_Islands(
      "UM", "UMI", "United States Minor Outlying Islands"),
  Uruguay("UY", "URY", "Uruguay"),
  United_States("US", "USA", "United States"),
  Uzbekistan("UZ", "UZB", "Uzbekistan"),
  Vatican_City("VA", "VAT", "Vatican City"),
  Saint_Vincent_and_the_Grenadines(
      "VC", "VCT", "Saint Vincent and the Grenadines"),
  Venezuela("VE", "VEN", "Venezuela"),
  British_Virgin_Islands("VG", "VGB", "British Virgin Islands"),
  United_States_Virgin_Islands("VI", "VIR", "United States Virgin Islands"),
  Vietnam("VN", "VNM", "Vietnam"),
  Vanuatu("VU", "VUT", "Vanuatu"),
  Wallis_and_Futuna("WF", "WLF", "Wallis and Futuna"),
  Samoa("WS", "WSM", "Samoa"),
  Yemen("YE", "YEM", "Yemen"),
  South_Africa("ZA", "ZAF", "South Africa"),
  Zambia("ZM", "ZMB", "Zambia"),
  Zimbabwe("ZW", "ZWE", "Zimbabwe");

  const Countries(this.iso_3166_1_alpha2, this.iso_3166_1_alpha3, this.name);
  final String name;
  final String iso_3166_1_alpha2;
  final String iso_3166_1_alpha3;
}
